const WORLD_HEIGHT = 800;
const WORLD_WIDTH  = 800;
const VIEWPORT_HEIGHT = 800;
const VIEWPORT_WIDTH  = 800;
const MAX_NODES = 1000;
const PEAK_DISTRIBUTION = {
  55: 3,
  80: 5,
  92: 7,
  98: 9,
  100: 15
};

module.exports = {
  WORLD_HEIGHT: WORLD_HEIGHT,
  WORLD_WIDTH: WORLD_WIDTH,
  VIEWPORT_HEIGHT: VIEWPORT_HEIGHT,
  VIEWPORT_WIDTH: VIEWPORT_WIDTH,
  MAX_NODES: MAX_NODES,
  PEAK_DISTRIBUTION: PEAK_DISTRIBUTION
};
