const WORLD_HEIGHT = 1600;
const WORLD_WIDTH  = 1600;
const VIEWPORT_HEIGHT = 800;
const VIEWPORT_WIDTH  = 800;

module.exports = {
  WORLD_HEIGHT: WORLD_HEIGHT,
  WORLD_WIDTH: WORLD_WIDTH,
  VIEWPORT_HEIGHT: VIEWPORT_HEIGHT,
  VIEWPORT_WIDTH: VIEWPORT_WIDTH
};
